INSERT INTO `users` (email,password, firstname,lastname) values ('saravanan21@gmail.com','saravanan123', 'Saravanan', 'B');
INSERT INTO `authorities` (role,users_id) values ('ROLE_ADMIN',1);
INSERT INTO `users` (email,password, firstname,lastname) values ('ar1998pit@gmail.com','Arpit9876', 'Arpit', 'Srivastava');
INSERT INTO `authorities` (role,users_id) values ('ROLE_ADMIN',2);
INSERT INTO `users` (email,password, firstname,lastname) values ('nilanshuv@gmail.com','nilanshu12', 'Nilanshu', 'Vishesh');
INSERT INTO `authorities` (role,users_id) values ('ROLE_ADMIN',3);
INSERT INTO `users` (email,password, firstname,lastname) values ('sattv123@gmail.com','sattv321', 'Sattv', 'Agarwal');
INSERT INTO `authorities` (role,users_id) values ('ROLE_USER',4);
INSERT INTO `users` (email,password, firstname,lastname) values ('bhavyas22@gmail.com','bhavya123', 'Bhavya', 'Sharma');
INSERT INTO `authorities` (role,users_id) values ('ROLE_USER',5);